### ISSUE TITLE
shell: create the shell library and source from hands-on scripts

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basics#192]
Using shell sourcing approach, function like console_log can be developed at once since place, then reuse from the other shell scripts
E.g:
```
source /path/to/other_script.sh
# or
. /path/to/other_script.sh

```

**Comment by dcompanykrish** [comment]
@tungbq ,Can you explain more about how to use the shell sourcing approach to develop and reuse functions in shell scripts?  give me some guidance on how to get started 🙏? Thank you 🚀.
