### ISSUE TITLE
Shell Exercise 03 - Random Password Generator

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basics#364]
Random Password Generator: Create a script that generates a random password of a specified length.
Similar to #361 #363 

DoD:
- Add the problem description to https://github.com/tungbq/devops-basic/tree/main/topics/shell/excercise
- Add the solution to https://github.com/tungbq/devops-basic/tree/main/topics/shell/excercise/answers
- Link the problem description to the solution 
- Please refer to #361 for reference

**Comment by alirafatartist** [comment]
with javascript or what?

**Comment by tungbq** [comment]
Hi @alirafatartist, with shell script please. Thank you

**Comment by alirafatartist** [comment]
> Hi @alirafatartist, with shell script please. Thank you

i think you wanted it with javascript

but this is Chatgpt answer

```
#!/bin/bash

generate_password() {
  local length=$1
  local password=""

  for i in $(seq 1 $length); do
    # Generate a random byte and convert it to a printable ASCII character
    byte=$(od -An -N1 -i /dev/urandom | awk '{print $1}')
    char=$(echo $byte | awk '{printf "%c", $1}')
    password="${password}${char}"
  done

  echo "$password"
}

# Check if a length argument is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <password_length>"
  exit 1
fi

# Get the password length from command line argument
password_length=$1

# Generate and print the random password
random_password=$(generate_password "$password_length")
echo "Random Password: $random_password"
```

**Comment by tungbq** [comment]
Thanks @alirafatartist could you please open a Pull request to address this task?

**Comment by alirafatartist** [comment]
> Thanks @alirafatartist could you please open a Pull request to address this task?

Do you mean make file with this code and make pull request to this repo

**Comment by tungbq** [comment]
> > Thanks @alirafatartist could you please open a Pull request to address this task?
> 
> Do you mean make file with this code and make pull request to this repo

Yes, that's right. And if you want to contribute to this repo 😍

**Comment by alirafatartist** [comment]
> > > Thanks @alirafatartist could you please open a Pull request to address this task?
> > 
> > 
> > Do you mean make file with this code and make pull request to this repo
> 
> Yes, that's right. And if you want to contribute to this repo 😍

in any folder or what??

**Comment by tungbq** [comment]
Under folder https://github.com/tungbq/devops-basic/tree/main/topics/shell/excercise/answers
Please refer to https://github.com/tungbq/devops-basic/issues/361 for reference

**Comment by alirafatartist** [comment]
> Under folder https://github.com/tungbq/devops-basic/tree/main/topics/shell/excercise/answers Please refer to #361 for reference

check it !

**Comment by tungbq** [comment]
This task is still not resolved, welcome other contributors

**Comment by Jonathanlemon** [comment]
Hi @tungbq Can I tackle this?

**Comment by tungbq** [comment]
> Hi @tungbq Can I tackle this?

Thank you @Jonathanlemon I've just assigned it to you.
