### ISSUE TITLE
topic: add `CloudFormation` content

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basics#497]
topic: add `CloudFormation` content
doc: https://aws.amazon.com/cloudformation/

Follow the https://github.com/tungbq/devops-basic/blob/main/templates/TOPIC_TEMPLATE.md to have the standard concept for all topics.

**Comment by anurag-compile** [comment]
hey @tungbq assign this to me please

**Comment by tungbq** [comment]
Sure, I've just assigned it to you. Thank you
