### ISSUE TITLE
Add README file with short introduction for `helm`

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basics#63]
In https://github.com/tungbq/devops-basic/tree/main/helm, make some updates:
- Create new README.md file
- Provide a short description to describe `what Helm is`
- Add the getting started link to README.md: `https://helm.sh/docs/intro/quickstart/`
- (Optional) It would be nice if we could have some other references/examples that make people getting started with helm in the README file

Reference: https://helm.sh/

**Comment by basu-10** [comment]
Hi, Just stumbled upon your repo and this issue as its tagged as "good first issue". Which is perfect for me. 
I haven't made any public commit yet.
I have a bit of knowledge working with Kubernetes and  helm, and was  I was hoping to jump in and make a contribution here. Let me know how I can get started!

**Comment by tungbq** [comment]
> Hi, Just stumbled upon your repo and this issue as its tagged as "good first issue". Which is perfect for me. I haven't made any public commit yet. I have a bit of knowledge working with Kubernetes and helm, and was I was hoping to jump in and make a contribution here. Let me know how I can get started!

Thanks @basu-10 for jumping into this repo. I've updated the description and you can start with it. Just add a README.md file provide a reference for people to start exploring `helm`

**Comment by tungbq** [comment]
Hi @basu-10 do we have any updates on this?

**Comment by basu-10** [comment]
Hello, apologies for the delay. I was stuck with with work and some other stuff. Here's what I've done till now. It still needs a bit more work. It'd be great if you can comment in this notion page (if I have enabled the option correctly) any relevant info/instruction: https://basu-10.notion.site/helm-documentation-for-github-f8826d7edc41454180977eb93dc24fb0?pvs=4

**Comment by tungbq** [comment]
> Hello, apologies for the delay. I was stuck with with work and some other stuff. Here's what I've done till now. It still needs a bit more work. It'd be great if you can comment in this notion page (if I have enabled the option correctly) any relevant info/instruction: https://basu-10.notion.site/helm-documentation-for-github-f8826d7edc41454180977eb93dc24fb0?pvs=4

It's look very nice and informative @basu-10. Appreciated for the effort 😍 
Just F.Y.I that recently we did add some content to the Helm/README.md as well. Please check that
I'd like to keep the README.md file as simple:https://github.com/tungbq/devops-basic/blob/main/topics/helm/README.md
So, I suggest creating another file like HELM_INTRODUCTION.md, then add a new section of README.md to link to that new file which contains all your work and content of Helm
![image](https://github.com/tungbq/devops-basic/assets/85242618/d78cd676-13c0-41bb-8a37-7e61664fe784)
