### ISSUE TITLE
warning: LF will be replaced by CRLF 

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basics#89]
Need to fix it:
warning: LF will be replaced by CRLF

**Comment by khanumar03** [comment]
is it  still  open ?

**Comment by tungbq** [comment]
> is it still open ?

Yes @khanumar03 , still valid now

**Comment by khanumar03** [comment]
its  just a  warning you can fix it by changing lf to crlf in vscode  it should be change automatically but i  don't know it's a bug  onr other problem 
![Screenshot 2023-08-27 150708](https://github.com/tungbq/devops-basic/assets/125285100/cc1ff05d-585f-4fbb-a19b-1182c49f1852)

**Comment by tungbq** [comment]
Hello, sorry for the late response:
I think we could apply the .gitattributes config for this repo to overcome the issue, despite the dev environment
See: 
- https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#example
- https://www.git-scm.com/docs/gitattributes#_end_of_line_conversion
